"""Add dedup_signature and risk scoring columns to alerts

Revision ID: 2ca0cc5761b5
Revises: 4f168737b4d6
Create Date: 2026-09-03 11:03:40.845724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca0cc5761b5'
down_revision: Union[str, Sequence[str], None] = '4f168737b4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('dedup_signature', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('risk_score_breakdown', sa.JSON(), nullable=True))
    op.add_column('alerts', sa.Column('investigation_priority', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_alerts_dedup_signature'), 'alerts', ['dedup_signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_dedup_signature'), table_name='alerts')
    op.drop_column('alerts', 'investigation_priority')
    op.drop_column('alerts', 'risk_score_breakdown')
    op.drop_column('alerts', 'risk_score')
    op.drop_column('alerts', 'dedup_signature')
    # ### end Alembic commands ###
