"""Initial schema

Revision ID: 4f168737b4d6
Revises: 
Create Date: 2026-08-29 16:42:53.272943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f168737b4d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_product', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('privilege_level', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'value', name='uq_entity_type_value')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('overall_risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitre_techniques',
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('technique_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('external_alert_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_product', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_ip', sa.String(length=64), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('parent_process', sa.String(length=255), nullable=True),
    sa.Column('command_line', sa.String(length=4000), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('cloud_account', sa.String(length=255), nullable=True),
    sa.Column('authentication_context', sa.JSON(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('existing_mitre_attack_mapping', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dedup_group_id', sa.String(length=36), nullable=True),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_connector_id'), 'alerts', ['connector_id'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_group_id'), 'alerts', ['dedup_group_id'], unique=False)
    op.create_index(op.f('ix_alerts_destination_ip'), 'alerts', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_alerts_domain'), 'alerts', ['domain'], unique=False)
    op.create_index(op.f('ix_alerts_file_hash'), 'alerts', ['file_hash'], unique=False)
    op.create_index(op.f('ix_alerts_hostname'), 'alerts', ['hostname'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_alerts_username'), 'alerts', ['username'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('investigation_priority', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=4000), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('false_positive_hypotheses', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_alert_id'), 'ai_analysis', ['alert_id'], unique=False)
    op.create_table('analyst_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('analyst_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_feedback_alert_id'), 'analyst_feedback', ['alert_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_alert_id'), 'events', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_alert_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_analyst_feedback_alert_id'), table_name='analyst_feedback')
    op.drop_table('analyst_feedback')
    op.drop_index(op.f('ix_ai_analysis_alert_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_alerts_username'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_hostname'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_file_hash'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_domain'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_destination_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_group_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_connector_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('mitre_techniques')
    op.drop_table('incidents')
    op.drop_table('entities')
    op.drop_table('connectors')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
